### PR TITLE
Update the search button width on small screens

### PR DESCRIPTION
**Pull request by PerkinsDan**
### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation
- [X] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
Changed the width of the purple search button on small screens so that it covers the whole screen. This makes it easier to press with one hand and looks better as it isn't left aligned and matches the search bar width

### Share a screenshot of new changes

Before
Before

After
iAfter

### CODE REVIEW

**Comment by Njong392** [comment]
:thinking: This looks great! I didn't think about it, so thank you :heart: I'm just worried that there's not enough or too little space now between the search button, and the text below it. What do you think?

**Comment by PerkinsDan** [comment]
Could be worth adding some more padding. Potentially more on top and bottom

**Comment by Njong392** [comment]
I think that'll look great. Will you update your PR?

**Comment by PerkinsDan** [comment]
Will do when I get back from work

**Review by Njong392 — APPROVED** [review]
Looks amazing! Thank you so much for contributing to abbreve ❤️

**Pull request merged**
