### PR TITLE
feat(slang) : Add IKYFL

### LINKED ISSUE #271: ABBREVIATION: <IKYFL>
### Description

Want to Add: IKYFL = "I Know You Fucking Lying"

### PR DESCRIPTION
**Pull request by Devanshukoli**
Closes #271 

### What new changes did you make? Tick all applicable boxes
- [x] Added new abbreviation
- [ ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### The Screenshot is here.
ikyfl

### CODE REVIEW

**Comment by Devanshukoli** [comment]
I have created PR as Mentioned in Readme.md file. Could you please review it? @Njong392

**Review by Njong392 — COMMENTED** [review]
Did you search on the site before opening this PR? I merged a pull request a few minutes ago that includes this abbreviation already. Looks like someone beat you to it, buddy.

**Comment by Devanshukoli** [comment]
@Njong392 I have tested it on **Abbreve** site. 
site

- And I have included a SS as well. Here. Are you sure about that? Because it still doesn't show up on the website when we search. If someone already Added it. Then, it's fine.
- If possible could you review it once more, please?

**Comment by Njong392** [comment]
I really remember seeing it in a pull request that I reviewed. It hasn't been merged yet though. I'll check again, and then get back to you.

**Comment by Devanshukoli** [comment]
Ok, No problem. @Njong392 😁 Thanks for putting in so much effort though. Really appreciate it.👋😎

**Comment by Njong392** [comment]
Okay wait. It seems that when I assigned the issue to you, I wasn't paying attention. Then I saw the PR and thought I has seen the same pull request before haha. I am sorry, it is my mistake.

**Comment by Njong392** [comment]
Okay wait. It seems that when I assigned the issue to you, I wasn't paying attention. Then I saw the PR and thought I has seen the same pull request before haha. I am sorry, it is my mistake.

**Comment by Njong392** [comment]
Okay wait. It seems that when I assigned the issue to you, I wasn't paying attention. Then I saw the PR and thought I has seen the same pull request before haha. I am sorry, it is my mistake.

**Comment by Njong392** [comment]
Okay wait. It seems that when I assigned the issue to you, I wasn't paying attention. Then I saw the PR and thought I has seen the same pull request before haha. I am sorry, it is my mistake.

**Comment by Njong392** [comment]
Okay wait. It seems that when I assigned the issue to you, I wasn't paying attention. Then I saw the PR and thought I has seen the same pull request before haha. I am sorry, it is my mistake.

**Pull request merged**
