### PR TITLE
Adding new abbreviations

### LINKED ISSUE #117: New Abbreviations
### What would you like to share?

I have some new and common abbreviations to add: 
- gn - Good Night
- gm - Good Morning
- btw - By The Way
- yrr - You aRe Right
- ihtg - I Have To Go

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rupali-codes**
Closes #117 

### What new changes did you make? Tick all applicable boxes
- [x] Added new abbreviation
- [ ] Added a new feature
- [ ] Fixed something in the source code
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.

Adding new abbreviations: 
- gn
- btw
- yrr
- ihtg
- wru
- if
- it 
- is
- ip
- cs
- cse
- isp
- dns

### CODE REVIEW

**Comment by Njong392** [comment]
@rupali-codes please recheck the README file. The structure of storing Abbreviations has changed. Also, I see that some changes have been made to the `package.json` and `CHANGELOG.md` file. Could you please revert? If you need guidance with that you can tell here.

**Comment by rupali-codes** [comment]
Hey @Njong392 I've made my changes, can you please review it. Thanks

**Review by Njong392 — CHANGES_REQUESTED** [review]
I think it's safe to remove `isp`, `it`, `dns` and `cs` as they don't exactly identify as slang

**Review by Njong392 — CHANGES_REQUESTED** [review]
`IP` is still here @rupali-codes I think you can take it out. Also, before you make changes, please sync your fork with this repo and pull from the main branch before you commit and push any new changes.

**Comment by rupali-codes** [comment]
sure Emy!

**Pull request merged**
