### PR TITLE
updated the db.json file with some new acronyms

### PR DESCRIPTION
**Pull request by theselaw**
updated the db.json file with some new acronyms, making use of the website to avoid duplicates.

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by PriyansuMaurya** [comment]
Brother write the acronyms you have added in the `db.json` file. It would be nice for the **reviewer** to check the _deployment_ without looking at the code.

**Review by Mohammed-Shoaib01 — COMMENTED** [review]
Hey @theselaw!

Looks like the way to [Add an Abbreviation](https://github.com/Njong392/Abbreve#adding-an-abbreviation) has changed, have a look at it!

Also might be a good idea to edit this PR's first comment to add a short description!

**Comment by Njong392** [comment]
@theselaw how is this coming along?

**Comment by Njong392** [comment]
Hello @theselaw are you still up for updating this? You'll have to check the abbreviations again because many of them have changed, and also the README because the method of adding abbreviations has also changed. If this PR stands for too long, I'll have to close it.

**Comment by Njong392** [comment]
I'm sorry but I will have to close this PR. I has been stagnating for a while. Feel free to checkout more issues you may want to work on. Thank you nonetheless for your contribution.

**Pull request closed without merging**
