### PR TITLE
Adding new Abbreviations

### LINKED ISSUE #172: [New Abbreviations]
### What would you like to share?

I was talking to one of my friend and I got something to add!

- idts - I Don't think So
- idli -  I Don't Like It
- ili - I Like it

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rupali-codes**
Closes #172

### What new changes did you make? Tick all applicable boxes
- [x] Added new abbreviation
- [ ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
added the following abbreviations
-idli
-idts
-ili

### CODE REVIEW

**Comment by Njong392** [comment]
Do you run `npm install` again and again when you need to do a new contribution?

**Comment by Njong392** [comment]
I'd like to think it's normal, because you pulled in the new changes from the upstream repo, and so your pr is reflecting the updated changes as well. But it's true. It's kind of strange. Thoughts @adropofilm and @ctoffanin ?

**Comment by ctoffanin** [comment]
Yeah, something is weird indeed. 
Probably something is not going well between the original fork and the sync.
You can't have a more updated changelog than the main branch unless you generated it.

The options now are:
- you fix your PR by removing package.json and changelog from your PR
- one of the maintainers remove the 2 files from here with a commit
- you close the PR and reopen a new one only staging the 3 files you want to add to the project

If you have weird conflicts, could be also a good idea to delete the fork and re-fork the repo again

As usual, this is my opinion and I'm not aware if there is a more easy way in github to ignore files from a PR.

**Comment by Njong392** [comment]
There is a way to cherry-pick but I'm not sure how that works with pull requests... Uhm... Maybe @rupali-codes can try this pr again without committing the changelog and package files. I'll do more research as to why they keep getting updated.

**Comment by rupali-codes** [comment]
Okay, Emy, I'll try to look for a way, and Thank you @ctoffanin

**Pull request closed without merging**
