### PR TITLE
Added a contributors section in the readme documentation

### PR DESCRIPTION
**Pull request by cleverhare**
Added a section for contributors, but old contributors will need to add their username as well by pasting and tweaking this. 

    <td align="center" style="word-wrap: break-word; width: 150.0; height: 150.0">
        <a href=https://github.com/cleverhare>
            
            <br />
            <sub style="font-size:14px"><b>Soumyajit Brahma</b></sub>
        </a>
    </td>

They need to provide their profile pic link and their names

### CODE REVIEW

**Comment by cleverhare** [comment]
If you want me to do it, I will do another commit as well. But because there area lot of contributors it will be great if everyone adds their own

**Comment by Njong392** [comment]
Wen you say provide their own details, you mean we individually have to ask the contributors?

**Comment by cleverhare** [comment]
I mean this time, I will add all the contributors but right from the next time, we will ask people to enter their names in a `JSON` File

**Comment by Njong392** [comment]
I see. I hope it is not too  much of a cumbersome task. For both you and the contributors.

**Comment by cleverhare** [comment]
yeahm they wont. its just that they needs to enter their github username

**Comment by Njong392** [comment]
I don't think this pull request is really making any progress, so I'll just go ahead and close it. Apologies if it didn't get merged.

**Pull request closed without merging**
