### PR TITLE
Added foss to db.json

### PR DESCRIPTION
**Pull request by Mohammed-Shoaib01**
## Changes proposed
Added the abbreviation for Free Open Source Software.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by adropofilm — APPROVED** [review]

**Review by adropofilm — CHANGES_REQUESTED** [review]
What Emy said ^

**Comment by Mohammed-Shoaib01** [comment]
Hey! Can we try running the tests again.

**Comment by Mohammed-Shoaib01** [comment]
Looks like it failed again, might need some guidance.

How about I Delete my fork and try a new PR?

Thank you for your time and advice!

**Comment by Njong392** [comment]
> 
> Thank you for your time and advice!

Oh. It failed again. Deleting your fork is an option. But did you try pulling?

**Comment by Mohammed-Shoaib01** [comment]
> > Thank you for your time and advice!
> 
> Oh. It failed again. Deleting your fork is an option. But did you try pulling?

Fork Sync

Is this the option I should be looking for? I've tried "Update Branch" from "Sync Fork".

**Comment by Njong392** [comment]
> Fork Sync
> 
> Is this the option I should be looking for? I've tried "Update Branch" from "Sync Fork".

Good thinking. That has updated your fork. Now in your terminal, in the working directory of your fork, run `git pull`

**Comment by Mohammed-Shoaib01** [comment]
> > Fork Sync
> > Is this the option I should be looking for? I've tried "Update Branch" from "Sync Fork".
> 
> Good thinking. That has updated your remote fork. Now in your terminal, in the working directory of your fork, run `git pull`

Doesn't seem to have made any changes

**Pull request closed without merging**
