### PR TITLE
Trying to add foss to db.json

### PR DESCRIPTION
**Pull request by Mohammed-Shoaib01**
## Changes proposed
Added the abbreviation for Free Open Source Software.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Mohammed-Shoaib01** [comment]
Sigh, Sorry for the trouble.

**Comment by Njong392** [comment]
> Sigh, Sorry for the trouble.

No worries! BOOM. This one passed. No need to apologise.

**Review by Njong392 — APPROVED** [review]
Yusss! Approved. Thank you for the contribution :1st_place_medal:

**Comment by Mohammed-Shoaib01** [comment]
Thank you for your support!!

**Pull request merged**
