### PR TITLE
feat(slang): added dfkm

### LINKED ISSUE #215: ABBREVIATION: <description>
### Description

Want to add new abbreviation dfkm

### PR DESCRIPTION
**Pull request by chibuike-19**
Closes #215 

### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation

### Describe the new changes you added.
Added a new slang dfkm

### CODE REVIEW

**Comment by Njong392** [comment]
Do you need help reverting the `package-lock.json` @chibuike-19 ?

**Comment by chibuike-19** [comment]
yes

**Comment by Njong392** [comment]
Where are u stuck? I'd like to help

**Comment by Njong392** [comment]
I'm sorry but I will have to close this PR. I has been stagnating for a while. Feel free to checkout more issues you may want to work on. Thank you nonetheless for your contribution.

**Pull request closed without merging**
