### PR TITLE
add: slang

### PR DESCRIPTION
**Pull request by JoseVale99**
Closes #

### What new changes did you make? Tick all applicable boxes
- [x] Added new abbreviation
- [ ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
I wanna give 2 suggestions:
1. your file name should be slang of the definition. 
2. capitalize definitions 

for example, create a `beat.json` for `Being Excellent At Something`

**Review by Njong392 — COMMENTED** [review]
Thank you very much for checking out our project.

Unfortunately, abbreve only accepts abbreviations, not full definitions like the ones you've added.

**Comment by JoseVale99** [comment]
> Thank you very much for checking out our project.
> 
> Unfortunately, abbreve only accepts abbreviations, not full definitions like the ones you've added.



> I wanna give 2 suggestions:
> 
> 1. your file name should be slang of the definition.
> 2. capitalize definitions
> 
> for example, create a `beat.json` for `Being Excellent At Something`

Excelent!

**Comment by JoseVale99** [comment]
Are these changes okay?

**Review by Njong392 — APPROVED** [review]
This looks super! Thank you so much for the new addition.

**Pull request merged**
