### PR TITLE
Added More Acronyms to Database.

### PR DESCRIPTION
**Pull request by ssaryonjr**
## Changes proposed
Added in 14 new data to database. These are acronyms used in urban areas.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by ssaryonjr** [comment]
Sounds good

**Comment by Njong392** [comment]
@ssaryonjr I would love to propose some new changes to this. The `db.json` has been updated and so have many other things. Please sync your fork with this, pull the new changes, and try updating your pull request with the changes I will suggest below.

**Review by Njong392 — CHANGES_REQUESTED** [review]
Unfortunately, we cannot accept certain abbreviations you have added to this. Please try removing slangs like `bbl`, `403`, `yt pple`, `yt`, `fnf`. Thank you.

**Comment by ssaryonjr** [comment]
Sounds good I'll get that done soon.

**Comment by Njong392** [comment]
@ssaryonjr is there any update with this? If you want to update this, please check the project README because we have updated the structure.

**Comment by Njong392** [comment]
Hello @ssaryonjr do you still have any plans on updating this pull request? If it's stagnating, I'm sorry but I'll have to close it. Do check out the README as I mentioned above that many new changes have been made.

**Comment by Njong392** [comment]
I'm sorry but I will have to close this PR. I has been stagnating for a while. Feel free to checkout more issues you may want to work on. Thank you nonetheless for your contribution.

**Pull request closed without merging**
