### PR TITLE
Added a new way to register slang

### PR DESCRIPTION
**Pull request by Abdulmumin1**
## Changes proposed
Added a new way to add slang's directly from the commandline

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshot
idk

## Note to reviewers
i just reduced the hassle of adding new slang 🤗

### CODE REVIEW

**Comment by Njong392** [comment]
Thank you very much for your contribution. If you check the `structure` branch of the repo, you can see that we are trying to create a different structure for the JSON objects. If each slang is a file of its own, then the possibility of have one slang exist twice will be highly uncommon.

**Review by Njong392 — APPROVED** [review]
Thank you the ALT text :tada: this commit is approved!

**Comment by Njong392** [comment]
Please revert the changes you have made in `package-lock.json` and the `package.json` files. Since only the changes you made to the README file have been approved, you can update your pull request.

**Comment by Abdulmumin1** [comment]
changes in the `readme` file is the documentation of the new feature added, am afraid revert changes in the `package-lock` and `package.json` may break the feature.

`package-lock.json` as the dependency to be installed
`package.json` as the script command to be ran.

if the new `structure` still involve contributors to open the `db.json` to add new abbreviation, then using this `feature` is much more easier.

what do you think?

**Comment by Njong392** [comment]
> changes in the `readme` file is the documentation of the new feature added, am afraid revert changes in the `package-lock` and `package.json` may break the feature.
> 
> `package-lock.json` as the dependency to be installed `package.json` as the script command to be ran.
> 
> if the new `structure` still involve contributors to open the `db.json` to add new abbreviation, then using this `feature` is much more easier.
> 
> what do you think?

If you check the README, you'll see that we have kind of changed the structure of the way slang are saved. A similar PR to yours was opened at #108 and that kind of creates a better cli solution considering the new structure. Perhaps you can have a look at it and add to that conversation?

**Pull request closed without merging**
