### PR TITLE
chore: added lmao

### PR DESCRIPTION
**Pull request by xasterKies**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by xasterKies** [comment]
Really, I did not even touch it 😅

**Comment by xasterKies** [comment]
I think I found why your saying that. You didnot set a gitignore on package-lock.json😅, should I do it?

**Comment by Njong392** [comment]
> I think I found why your saying that. You didnot set a gitignore on package-lock.jsonsweat_smile, should I do it?

Some online resources for example [this one](https://dev.to/shrihankp/comment/1b213) advise that we don't ignore the `package-lock.json` or `package.json` files. 

You can check [this resource](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a) out to help with the revert.

**Review by adropofilm — CHANGES_REQUESTED** [review]
Please resolve merge conflicts with `db.json` as well. Other than that + what Emy mentioned, looks good.

**Comment by xasterKies** [comment]
Hey @adropofilm , just did the package-lock.json revert. As for the merge confilct I think its because the space I added the lmao abbreviation was already occupied by some other ones in the main considering some merges happened bettwen yesterday and now. What I did was move it the bottom of the JSON instead.

**Review by adropofilm — APPROVED** [review]

**Comment by adropofilm** [comment]
Everything looks good just one last change @xasterKies. Please capitalize the first letter of each word in the definition, and then we can merge. 

`
"Laughing My Ass Off"
`

instead of

`
"Laughing my ass off"
`

**Review by adropofilm — CHANGES_REQUESTED** [review]
Everything looks good just one last change @xasterKies. Please capitalize the first letter of each word in the definition, and then we can merge. 

`
"Laughing My Ass Off"
`

instead of

`
"Laughing my ass off"
`

**Comment by xasterKies** [comment]
Done @adropofilm

**Comment by adropofilm** [comment]
Looks good @xasterKies, one last thing. Can you please resolve the conflicts in db.json and sync your fork with this repo? It's 47 commits behind.
Screen Shot 2022-10-05 at 6 19 53 PM

**Pull request closed without merging**
