### PR TITLE
added cfbr abbreviation

### PR DESCRIPTION
**Pull request by abhiraj-ku**
This Issue adds a new Abbreviation i.e CFBR

Closes #

### What new changes did you make? Tick all applicable boxes
- [ yes] Added new abbreviation
- [ ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
Added cfbr and its description as suggested by guidelines

### CODE REVIEW

**Comment by abhiraj-ku** [comment]
Hey @Njong392 . I have added Cfbr abbreviation . please review and suggest if any change is required ..

Thanks in Advance

**Review by Njong392 — CHANGES_REQUESTED** [review]
Thank you so much for the addition, but you made the addition to the wrong file. You should create a file, in the location `public/server/db/cfbr.json` and then add your abbreviation to it. If you need any help, do ask, or refer to the README and contributing.md.

**Comment by abhiraj-ku** [comment]
hey @Njong392 i have made changes as you requested . I hope this time its ok . please let me know any further changes that is to be made.

Thanks for reviewing

**Review by Njong392 — APPROVED** [review]
Is perfect now! Thank you for the stellar addition 🎉

**Comment by abhiraj-ku** [comment]
cfbr2

Thanks for merging . It Feels good to Contribute to open source projects. Looking forward to contribute more on this interesting projects

**Comment by Njong392** [comment]
Thank you for the superb addition again! Looking forward to more contributions from you, fren!

**Comment by abhiraj-ku** [comment]
sure , i will try to add more valuable contributions to this project

**Pull request merged**
