### PR TITLE
change on a:hover color to white

### LINKED ISSUE #16: Change a:hover color
### Description

Hi everyone, 
There's not enough contrast between background color and text color when the user hovers over the Get Started link (navbar). 
I don't know if the text could be changed to a lighter color or just not have a change of color on hover since there's already a scale effect.

### Screenshots

Picture of the button on hover:
hover

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by glopzel**
## Fixes Issue

Closes #16 

## Changes proposed

Change color of a:hover from #646cff to #ffffff

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

| before | after |
|---|---|
| before | after |

### CODE REVIEW

**Comment by Njong392** [comment]
Unfortunately, the changes you made didn't affect the button. I think it has something to do with the method I used for the scroll. I'll try to look into this. But if you want to have another go at it, let me know :smile: Thank you for the contribution!

**Comment by glopzel** [comment]
it could be related to that Link import and also to not changing the a:hover color on the media feature

**Comment by Njong392** [comment]
> it could be related to that Link import and also to not changing the a:hover color on the media feature

I really wonder what the problem is.

**Review by adropofilm — APPROVED** [review]
Functions as expected & is pleasing to the eye. LGTM!

Screen Shot 2022-10-04 at 6 33 32 PM

**Pull request merged**
