### PR TITLE
fix: left hero content displacement fix

### LINKED ISSUE #88: Put a word-wrap property for the => | errorMessage & isUserInputBlank | text which appear when either of both States are true.
### Description

When we put wrong slang or slang that is not present or the search bar is empty, we get a msg telling us the real problem like 
this 

**1.  When slag is not present**

    - This entry does not exist in our records as of yet :(

      1. You can help us add this by creating a [github issue](https://github.com/Njong392/Abbreve)

      2. Or, you could fill out this [feedback form](https://t.co/mp86BLYBhq) and we will address the issue
      
**2.  When SearchBar is Empty**

    - Search bar 🔍 is Empty!. Please put abbreviation in search bar    

But when either of these messages appears, _the content on its left gets displaced slightly to the left_. **it will more clear from the SS I have added below.**

### Screenshots

Screenshot (6)

Screenshot (7)

Screenshot (9)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TropicolX**
Closes #88

### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation
- [x] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
Added a max-width utility class to the right hero content's list of classes, so it has a max width of `22.5rem`. This way, it doesn't expand beyond that width when its content changes and, as a result, displace the left content.

### Share a screenshot of new changes

Screenshot 2023-01-18 175106
Screenshot 2023-01-18 175142
Screenshot 2023-01-18 175204

### CODE REVIEW

**Comment by Njong392** [comment]
Thank you so much for the changes you made. It seems that your PR came with some changes to the `package-lock.json` file. To prevent future complications on the main branch, it is advisable that you revert these changes. You can check [here](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a) on how to do that.

**Comment by PriyansuMaurya** [comment]
Good but it seems still there is a small thing to be fixed --> displacement to the top

look here 

Screenshot (28)

**Comment by Njong392** [comment]
Oh wow. I didn't catch this on my browser. Thanks for highlighting it @PriyansuMaurya 

Can you take a look at that @TropicolX ?

**Comment by Njong392** [comment]
@TropicolX are you still working on this pull request?

**Comment by Njong392** [comment]
I'm sorry but I will have to close this PR. I has been stagnating for a while. Feel free to checkout more issues you may want to work on. Thank you nonetheless for your contribution.

**Pull request closed without merging**
