### PR TITLE
change position of loading component for better ux

### LINKED ISSUE #286: BUG: <description>
### Description

The loading when we search for abbreviation, is outside of input panel

dosen't sound good in terms of ui

would be better to have loading inside search button which is by toggling innerText of button with Loading panel

### Screenshots

https://user-images.githubusercontent.com/91718608/222051989-6025826d-8425-442e-b120-678ab8906d14.mp4

### PR DESCRIPTION
**Pull request by abhijain2003**
Closes #286 

### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation
- [ ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
I change position of Loading component inside form.jsx file, which was outside of button and aligned at bottom start/left,  was not looking good for user experience purpose, so , I put it inside button

it's like toggling innerText of button with LoadingComponent

### CODE REVIEW

**Review by Njong392 — COMMENTED** [review]
Whoa. This is looking really neat! Thank you for the changes. However, I think your changes came with some unwarranted adjustments to the `package-lock.json`. Could you please revert those?

**Comment by abhijain2003** [comment]
can you help me, I am bit beginner at this

**Comment by Njong392** [comment]
> can you help me, I am bit beginner at this

Sure! You can check out this short [github gist](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a) here.

**Comment by abhijain2003** [comment]
done bro

**Pull request merged**
