### PR TITLE
new abbreviations added

### PR DESCRIPTION
**Pull request by Abbeyafolaby**
Screenshot (47)

Closes #

### What new changes did you make? Tick all applicable boxes
- [x] Added new abbreviation
- [ ] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
good ones

**Comment by Abbeyafolaby** [comment]
> good ones

Thank you!!

**Review by Njong392 — CHANGES_REQUESTED** [review]
Hey there! Thank you so much for contributing to Abbreve. You've made some stellar additions 💣 

I see that you may have committed changes to the `package-lock.json`. This may cause issues for the main branch later. To revert, you can check out [this guide](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a)

**Comment by Abbeyafolaby** [comment]
> Hey there! Thank you so much for contributing to Abbreve. You've made some stellar additions 💣
> 
> I see that you may have committed changes to the `package-lock.json`. This may cause issues for the main branch later. To revert, you can check out [this guide](https://gist.github.com/kumarsonsoff3/fbc6ecde519250a9f0a4d7ccc9993a1a)

Alright, I will do that. Thanks

**Comment by Abbeyafolaby** [comment]
Hi, I have revert the commit on the `package-lock.json`. 
I hope it is okay?

**Review by Njong392 — APPROVED** [review]
You've made some pretty stellar additions! Thank you so much for contributing to abbreve.

**Pull request merged**
