### PR TITLE
updated

### PR DESCRIPTION
**Pull request by BLXCKVLEN**
Closes #

### What new changes did you make? Tick all applicable boxes
- [x] Added new abbreviation
- [x] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### CODE REVIEW

**Comment by Njong392** [comment]
I'm sorry if it's just me being really lost, but I don't know what issue this pull request closes. The preview takes me to a blank page with a checkbox. Could you please clarify me?

**Comment by BLXCKVLEN** [comment]
I'm having the same issue gimme a time I'll try again

**Comment by BLXCKVLEN** [comment]
Dark Mode to Light mode bug issue was cleared

**Comment by Njong392** [comment]
When you say cleared I don't understand. Your changes don't explain much. Are you still working on this?

**Comment by Njong392** [comment]
I'm sorry but I will have to close this PR. I has been stagnating for a while. Feel free to checkout more issues you may want to work on. Thank you nonetheless for your contribution.

**Pull request closed without merging**
