### PR TITLE
Fix for dark mode toggle

### PR DESCRIPTION
**Pull request by gajanandh**
Closes # 383

### What new changes did you make? Tick all applicable boxes
- [x] Fixed something in the source code

### Describe the new changes you added.
Dark mode toggle was not working on first page visit due to incorrect Boolean set on toggle theme state. Changed it to fix the issue

### CODE REVIEW

**Review by Njong392 — CHANGES_REQUESTED** [review]
Thank you so much for catching this! I must've merged without paying much attention. But with your changes, the same thing still happens. When the page first loads, based on the toggle, it says it's supposed to be in dark mode but the theme is light. When I then switch the theme to light, the icon toggles. And I checked localStorage just in case, and the value for `theme` is actually inverted so when it's light theme, the value says dark instead and vice versa.

abbreve

**Comment by gajanandh** [comment]
I have made necessary changes, Please review the changes

**Comment by Njong392** [comment]
Thank you! You've fixed it, but when the theme is light, it's the moon icon that shows instead of the sun. Perhaps you could switch that and I think then it'd be perfect.

**Comment by gajanandh** [comment]
The icon is not indicating current theme but the one which it  should be toggled to,  like if it is dark mode the sun icon will indicate that it is the button to chage to light theme. It is similar in many websites.

**Comment by gajanandh** [comment]
Tailwind website uses a different approach, they use icon button for opening drop-down and there we have select mode. There is similar implementation on bootstrap website, but ours is direct toggle button so it makes sense to place icon which we want to switch to.
Here are some websites which use direct toggle, https://react.dev https://chakra-ui.com/ https://www.solidjs.com/

**Comment by Njong392** [comment]
Oh, I now see what you mean. Apologies for being a little clueless. Thank you so much for the PR again.

**Pull request merged**
