### PR TITLE
fix: sanitize user input (#128)

### LINKED ISSUE #128: User input is not sanitize before making a request resulting to send all contents of db.json file.
### Description

User input is not sanitize before making a request.
Adding `../db` as form input results to send the whole content of `db.json` file.

I suggest to sanitize user input before sending a request.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by reny-pacheco**
Closes #128

### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation
- [x] Fixed something in the source code
- [ ] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
Sanitized user input during `keypress` and `on paste` event.
Form only accepts `[a-zA-Z]` values.

Copied value: `   aBc-12c d/e.f   `
Pasted value: `aBccdef`

### Share a screeshot of new changes
I tried to input again the malicious value `../db`  and here is the screenshot of the output. It only displays `db`

image

### CODE REVIEW

**Comment by mathiasayivor** [comment]
@reny-pacheco I suggest you improve on the regex for sanitizing inputs cos I don't think the current implementation supports abbreviations with special characters, e.g `w/o`.

I suggest you use the `encodeURIComponent` function instead.

**Comment by reny-pacheco** [comment]
Good catch @mathiasayivor , I'll try to use `encodeURIComponent`. Thank you.

**Comment by reny-pacheco** [comment]
Hello, apologies for not having an update, you can assign this to another contributor if they want to work on this. Thank you.

**Comment by Njong392** [comment]
@mathiasayivor you mentioned something about certain inputs not being accepted because of the sanitation. Would you have an idea related to this pull request?

**Comment by mathiasayivor** [comment]
> @mathiasayivor you mentioned something about certain inputs not being accepted because of the sanitation. Would you have an idea related to this pull request?

Yeah

**Comment by mathiasayivor** [comment]
`encodeURIComponent` is the best option for sanitizing user inputs, since it's used in the CLI for encoding.

I'd also recommend using the `encodedAbbrMappings.json` in addition to `encodeURIComponent` to be sure the searched slang doesn't exist before sending the final result to the user.

Demo below:
```
search -> sanitize user input (`encodeURIComponent`)
                                                   |
                                          search abbrev -> found result? -> show slang definition
                                                   |
                                             No result?
                                                   |
                           check encodedAbbrMappings.json -> found result? -> show slang definition
                                                   |
                                             No result?
                                                   |
                           Display Result not found error
```

**Comment by Njong392** [comment]
I see... kind of hahaha. Do you want to go for it @mathiasayivor ? Maybe contribute to @reny-pacheco fork.

**Comment by mathiasayivor** [comment]
> I see... kind of hahaha. Do you want to go for it @mathiasayivor ? Maybe contribute to @reny-pacheco fork.

Sure... But I'm not sure if I have write access to @reny-pacheco's fork...

**Comment by mathiasayivor** [comment]
Perhaps I could just create a new PR by copying @reny-pacheco's changes?

**Comment by reny-pacheco** [comment]
> > I see... kind of hahaha. Do you want to go for it @mathiasayivor ? Maybe contribute to @reny-pacheco fork.
> 
> Sure... But I'm not sure if I have write access to @reny-pacheco's fork...

Hi @mathiasayivor , If you doesn't have access, I can give you access to the fork.

**Comment by mathiasayivor** [comment]
Sure... That'd be great!

**Comment by reny-pacheco** [comment]
> Sure @reny-pacheco ... That'd be great!

@mathiasayivor , I've already added you  as contributor to the fork, can you confirm that?

**Comment by mathiasayivor** [comment]
> > Sure @reny-pacheco ... That'd be great!
> 
> @mathiasayivor , I've already added you as contributor to the fork, can you confirm that?

Seen

**Comment by mathiasayivor** [comment]
Alright fellas, I think we're good to go!
@Njong392 @reny-pacheco @adropofilm reviews are welcomed.

**Review by reny-pacheco — COMMENTED** [review]
Hi @mathiasayivor , I suggest to add a guard clause in line 31, to prevent fetching of `encodedAbbrMappings` if search field is empty. I found out that if you click submit with empty value. It still fetch the data.

Suggestion: 
```
const fetchData = async (query) => {
   if(!userInput.trim()) {
      return
    } 
    let mappings;
    ...
    ...

```

**Comment by mathiasayivor** [comment]
> Hi @mathiasayivor , I suggest to add a guard clause in line 31 of `form.jsx` file, to prevent fetching of `encodedAbbrMappings` if search field is empty. I found out that if you click submit with empty value. It still fetch the data.
> 
> Suggestion:
> 
> ```
> const fetchData = async (query) => {
>    if(!userInput.trim()) {
>       return
>     } 
>     let mappings;
>     ...
>     ...
> ```

Sure...

**Comment by reny-pacheco** [comment]
LGTM, Thanks @mathiasayivor 😃

**Comment by Njong392** [comment]
Yikes... the whole code became something different haha. Still trying to wrap my head around it. But... when the user enters a slang that doesn't exist, it just says "some connection error occurs". Shouldn't it warn the user that the slang doesn't exist and they could raise an issue as before?

**Comment by mathiasayivor** [comment]
> Yikes... the whole code became something different haha. Still trying to wrap my head around it. But... when the user enters a slang that doesn't exist, it just says "some connection error occurs". Shouldn't it warn the user that the slang doesn't exist and they could raise an issue as before?

This works on the local dev env:
Screenshot from 2022-10-26 12-34-32


The error you're getting is the expected behaviour, since the server is responding with 200 status instead of 404.

**Comment by mathiasayivor** [comment]
I think the error you're getting is an issue with how vercel's routing works,

Screenshot from 2022-10-26 12-39-27

The expected response, in this case, is `404` but the server is returning `200` with HTML as content type, hence the app is unable to parse HTML as JSON, thence the error.

**Comment by Njong392** [comment]
I see. Is there a fix to this? Or we just blame it on vercel 😂

**Comment by reny-pacheco** [comment]
Hi @mathiasayivor , on my fork, I created a branch named `simplified-fetch` that may fix 404 issue , since previously we are explicitly comparing the status code. Maybe you can check it since you have already access on my fork.

**Comment by mathiasayivor** [comment]
> I see. Is there a fix to this? Or we just blame it on vercel 😂

Perhaps do additional checks(i.e ensuring response is a valid JSON) if the response status is 200.

**Comment by Njong392** [comment]
I am so lost on this pull request right now, so I am putting it off for a bit. Thank you @mathiasayivor and @reny-pacheco for the progress on this!

**Pull request closed without merging**
