### PR TITLE
added preset paramters and reading

### LINKED ISSUE #417: FEATURE: make definitions shareable
### Description

Currently, users can only lookup definitions, but it would also be great if there's a shareable link that users can share with others so they could easily view the definition instead of manually searching again

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by trp02**
Closes #417 

### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation
- [ ] Fixed something in the source code
- [X] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
Working on adding a feature that will make abbreviations sharable through a link.

### CODE REVIEW

**Comment by trp02** [comment]
Just wanted to update on the progress. About halfway done with the implementation. Few bugs that need to be worked out and then I'll work on the button design.

**Comment by Njong392** [comment]
@trp02 thank you for this! Take your time.

**Comment by trp02** [comment]
Hey @Njong392. I have ironed out the processing part of this feature. Would it be possible to merge this PR so I can ensure the file redirection works the same way on a central server as it does locally. I'm pretty sure it'll be fine but if not I will have to change just one line in the code. I have removed the button so users won't be able to see this feature just yet but I'll be able to test it by adjusting the URL parameters.

I will create a separate PR for the button itself and we can discuss and adjust the design there as needed.

**Comment by Njong392** [comment]
Hi there! Apologies for the delay, but I've been a little bit caught up. I will review this very soon. Thank you!

**Comment by Njong392** [comment]
Okayy the code looks okay-ish to me. Makes sense at least. Even on vercel preview I cannot see what u implemented, but let's merge like u said and see what happens.

**Comment by trp02** [comment]
you won't be able to see it yet because I haven't added the button for it. I will make a separate PR in the next few days with a proposed design and we can see if you like it.

**Pull request merged**
