### PR TITLE
Break db.json into small chunks

### LINKED ISSUE #47: [FEATURE] Break db.json to smaller chunks
### Description

Currently, there's only one db.json file, which contains all definitions and as the DB file grows (more definitions added) there'd be at least the following issues:
* Searches take time since the db.json file has to be downloaded on each search
* App becomes slow since the downloaded db.json file has to be stored in memory for each search request
* Adding new definitions become difficult since the text editor might become slow due to the huge db.json file
* It becomes difficult to sort abbreviations because the contributor has to manually go through each abbreviation in order to insert it into the appropriate place
* Frequent merge conflicts since all contributors are working on the same file
* Higher chances of duplicate abbreviations
* Reviewing PRs for adding new abbreviations becomes cumbersome

...plus many other possible issues

My proposal is, to split each abbreviation into its own file like below:
```
Abbreve
└public
└─server
└──db
│  │ gtm.json
│  │ lfg.json
│  │ idk.json
│  │ ...
```

Where each JSON file contains the definition of an abbreviation. The actual abbreviation would be the name of the JSON file.
Note: The structure of each abbreviation would still be the same, (I made a proposal for improving the structure in #42)

### Screenshots

_No response_

### Additional information

By using my proposed solution,
* Sorting becomes easier since it can be done by the file manager/text editor.
* Reviewing each PR for adding abbreviations becomes easier
* Fewer chances of merge conflicts for abbreviations
* Contributing/adding a new abbreviation becomes easy and simple
* Editing an abbreviation becomes easier
* No chances of duplicate abbreviation definitions

Caveats
Using my proposed solution means changing the structure of all abbreviations becomes difficult, but we can solve this by creating a simple app for changing the structure of all abbreviations.

### PR DESCRIPTION
**Pull request by mathiasayivor**
## Fixes Issue

Closes #47 

## Changes proposed

* Break db.json into small chunks of definitions
* Provide tools for managing db chunks

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Njong392** [comment]
I do not know what I am doing wrong haha. Had to switch up the path of the run command for mine to run, and when it did, there was an error 
Screenshot from 2022-10-05 09-38-12

**Comment by mathiasayivor** [comment]
> I do not know what I am doing wrong haha. Had to switch up the path of the run command for mine to run, and when it did, there was an error Screenshot from 2022-10-05 09-38-12

Oops. Which version of nodejs are you using?

**Comment by Njong392** [comment]
> > I do not know what I am doing wrong haha. Had to switch up the path of the run command for mine to run, and when it did, there was an error Screenshot from 2022-10-05 09-38-12
> 
> Oops. Which version of nodejs are you using?

v 17.2.0

**Comment by mathiasayivor** [comment]
Can you look through the README.md file and give me feedback on the added to-do items?
So we may start working on them

**Comment by Njong392** [comment]
> Can you look through the README.md file and give me feedback on the added to-do items? So we may start working on them

About the second todo, it's pretty clear. About the first and third, not so much. What caching strategies do you have in mind? And what structure are we referring to? The one you mentioned in #42 ?

**Comment by mathiasayivor** [comment]
> > Can you look through the README.md file and give me feedback on the added to-do items? So we may start working on them
> 
> About the second todo, it's pretty clear. About the first and third, not so much. What caching strategies do you have in mind? And what structure are we referring to? The one you mentioned in #42 ?

The first todo is about making the search function work with the new changes (individual JSON files)

The caching strategy is for searches.
Each time a definition is found after a search, either through a search suggestion (#76 ) or a direct search result, we simply save it to cache and re-use it when the user searches for the same abbrev again instead of making a new request.
Hence the search process looks like this:
Untitled Diagram

**Comment by Njong392** [comment]
Ok. Don't worry about the first and third todo. I tried them out on a new branch. About the second one, I'd really like for us to not dive too deep into caching, optimization, etc. The JSON is already pretty small in size with all the splitting that we've done thanks to you.

**Comment by mathiasayivor** [comment]
@Njong392 I'm a bit confused in terms of how you're labelling the todos...

**Comment by mathiasayivor** [comment]
1. Integrate current db structure into app's search engine.

2. Add instructions for contributing in main README.md

3. Add caching strategies for searched abbrevs

**Comment by Njong392** [comment]
> 1. Integrate current db structure into app's search engine.
> 2. Add instructions for contributing in main README.md
> 3. Add caching strategies for searched abbrevs

1. I was playing around with a branch today, and I managed to fix the first to-do.
2. The README is not a big deal. Once we merge this PR, we can update it.
3. Refer to my comment above.

**Comment by mathiasayivor** [comment]
> > 1. Integrate current db structure into app's search engine.
> > 2. Add instructions for contributing in main README.md
> > 3. Add caching strategies for searched abbrevs
> 
> 1. I was playing around with a branch today, and I managed to fix the first to-do.
> 2. The README is not a big deal. Once we merge this PR, we can update it.
> 3. my previous comment: [Break db.json into small chunks #64 (comment)](https://github.com/Njong392/Abbreve/pull/64#issuecomment-1268882499)

Ok it's all clear now

**Review by Njong392 — APPROVED** [review]
All looks pristine! Thank you for this new addition @mathiasayivor :tada: REALLY appreciated

**Comment by mathiasayivor** [comment]
@Njong392 I know this is late, but I have one essential quick fix that I need to add, which is abbreviations containing special characters
e.g w/o, etc

**Comment by mathiasayivor** [comment]
> @Njong392 I know this is late, but I have one essential quick fix that I need to add, which is for abbreviations containing special characters e.g w/o, etc

I think we're good to go now.

Explanation of new changes:
Files containing special characters are encoded to make saving possible.
Since encoded files are difficult to read/identify, I made provisions for a `public/server/encodedAbbrMappings.json` file, which contains a mapping of all encoded abbreviations to their original form.

**Review by adropofilm — APPROVED** [review]

**Comment by adropofilm** [comment]
Looks great, tested with special characters & function as expected.

Screen Shot 2022-10-06 at 2 01 00 AM

**Pull request merged**
