### PR TITLE
added the contributing.md

### LINKED ISSUE #4: [DOCS] Add CONTRIBUTING.md file
### Description

To help new contributors know exactly what to do and what to expect of the project...
 - [ ] We might need guidelines on how to fork, clone, push, etc
 - [ ] What kind of contributions we are looking for
 - [ ] Commit conventions, issue, and pull request templates
 - [ ] Links to resources, the code of conduct, etc

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Excellence-arch**
Closes #4 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

- You can add your contact address
- Please add hacktoberfest to the tags of the repository

### CODE REVIEW

**Comment by Njong392** [comment]
There are people already assigned to work on this, so I'll close this PR. If you have any suggestions to make concerning the contributing.md file, join the conversation under the issue itself.

**Comment by Excellence-arch** [comment]
> There are people already assigned to work on this, so I'll close this PR. If you have any suggestions to make concerning the contributing.md file, join the conversation under the issue itself.

Please add hacktoberfest to the repo topic

**Comment by Njong392** [comment]
> > There are people already assigned to work on this, so I'll close this PR. If you have any suggestions to make concerning the contributing.md file, join the conversation under the issue itself.
> 
> Please add hacktoberfest to the repo topic

`hacktoberfest-accepted` label will be added to your pull request if the maintainer sees it fit for hacktoberfest. Unfortunately, adding a new abbreviation to the json does not count.

**Comment by Njong392** [comment]
> > There are people already assigned to work on this, so I'll close this PR. If you have any suggestions to make concerning the contributing.md file, join the conversation under the issue itself.
> 
> Please add hacktoberfest to the repo topic

`hacktoberfest-accepted` label will be added to your pull request if the maintainer sees it fit for hacktoberfest. Unfortunately, adding a new abbreviation to the json does not count.

**Comment by Njong392** [comment]
> > There are people already assigned to work on this, so I'll close this PR. If you have any suggestions to make concerning the contributing.md file, join the conversation under the issue itself.
> 
> Please add hacktoberfest to the repo topic

`hacktoberfest-accepted` label will be added to your pull request if the maintainer sees it fit for hacktoberfest. Unfortunately, adding a new abbreviation to the json does not count.

**Pull request closed without merging**
