### PR TITLE
Upgrade abbreviations and logic

### PR DESCRIPTION
**Pull request by larsniet**
## Changes proposed

1. Add new abbreviations (not only slang words just in case).
2. Add abbreviation helper. The longer the list gets, the harder it is to check words.
3. Update form styling to stop it from jumping around when entering/removing a word.
4. Add useEffect hook to clear the error when user cleared the (faulty) input.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Njong392 — CHANGES_REQUESTED** [review]
Unfortunately, Abbreve is not exactly an 'urban' dictionary. We appreciate your contribution, but this addition will not fit with the purpose of the app, unfortunately.

**Review by Njong392 — COMMENTED** [review]
You will see this is my previous review, but yet again, these words won't fit for now. Hope you understand :+1:

**Review by Njong392 — COMMENTED** [review]
I love the changes you have made to this file! It improves a lot. But you have made too many changes to this pull request, and I don't know if git allows you to 'partially' merge pull requests.

**Comment by Njong392** [comment]
I have checked this, and yes. You can use `cherry pick` or something like that to merge only certain commits. I'll try to merge the cool change that you made to the file :100: and then we can close off the others. How's that?

**Comment by larsniet** [comment]
> I have checked this, and yes. You can use `cherry pick` or something like that to merge only certain commits. I'll try to merge the cool change that you made to the file 💯 and then we can close off the others. How's that?

Sounds good, before you do, I'll try to add some better slang words ;).

**Comment by larsniet** [comment]
Everything should be better now. I added a couple thousand abbreviations and updated the abbreviations-helper.js. This script can be used to check if the word you want to add is already in the database and it can filter the database (remove duplicates and sort).

**Comment by Njong392** [comment]
> Everything should be better now. I added a couple thousand abbreviations and updated the abbreviations-helper.js. This script can be used to check if the word you want to add is already in the database and it can filter the database (remove duplicates and sort).

Ok, so something new came up. Check out #47 which I think can replace the helper function you wrote. If each abbreviation is split into separate files, then there will hardly be any duplicates.

**Comment by Njong392** [comment]
Also, we have created a new branch to migrate the current structure to a new one. You have a lot of definitions, and if i merge your request, it'll cause difficulties during migration. Because of this, I'll leave this pull request open and after we change the database structure, we'll come back to it. What do you think?

**Comment by larsniet** [comment]
> Also, we have created a new branch to migrate the current structure to a new one. You have a lot of definitions, and if i merge your request, it'll cause difficulties during migration. Because of this, I'll leave this pull request open and after we change the database structure, we'll come back to it. What do you think?

New structure seems nice. It will definitely speed up the app. Did you consider using an actual database instead of plain JSON files, or do you think it's ok to have 10s of thousands of files (at some point) in the public folder?

Anyway, for now I'll just delete all my changes except the abbreviations file and create the JSON files following the new structure in this branch so that you can choose either one of the structures.

**Comment by Njong392** [comment]
> New structure seems nice. It will definitely speed up the app. Did you consider using an actual database instead of plain JSON files, or do you think it's ok to have 10s of thousands of files (at some point) in the public folder?
> 


I do plan on using a database. Just not at the moment. You want to create 1000 files for the new abbreviations you made? :laughing:

**Comment by larsniet** [comment]
> > New structure seems nice. It will definitely speed up the app. Did you consider using an actual database instead of plain JSON files, or do you think it's ok to have 10s of thousands of files (at some point) in the public folder?
> 
> I do plan on using a database. Just not at the moment. You want to create 1000 files for the new abbreviations you made? I think that would be quite too much.

Isn't that the whole point of the app? 😄 And yes. I'll push it in a sec.

**Review by Njong392 — COMMENTED** [review]
Unfortunately, I cannot merge this pull request. It is too big, and reviewing it is lagging my browser even. I do appreciate the contribution. You can contribute again, but in smaller chunks. Thank you.

**Pull request closed without merging**
