### PR TITLE
Added code will show msg [Search bar 🔍 is Empty!. Please put abbreviation in search bar ] when searched for  empty string.

### PR DESCRIPTION
**Pull request by PriyansuMaurya**

### CODE REVIEW

**Comment by Njong392** [comment]
An issue was created for this already. See #43. And someone was assigned. If they haven't worked on the issue yet, and they are okay with this, then we'll merge this one. How about that?

**Comment by PriyansuMaurya** [comment]
Okay great.

**Comment by Njong392** [comment]
> Okay great.

I think we can review this now.

**Review by Njong392 — CHANGES_REQUESTED** [review]
This is cool! But when the user starts typing something, the message is still present. Perhaps inside `useEffect` you can set `setIsUserInputBlank` to `false`?

**Review by Njong392 — APPROVED** [review]
Boom! Works fine now. Thanks again for this :heart:

**Pull request merged**
