### PR TITLE
Meta tag added

### LINKED ISSUE #175: FEATURE: Add meta info to the site
### Description

Currently, when we share the project link on some social media, for example, there is no preview image. It would be nice to have meta information so that when we share the link on Twitter, a nice card is generated with the site preview and a short description.
 
[Here](https://css-tricks.com/essential-meta-tags-social-media/) is a nice reference on meta tags. 

If we do decide to work on this, what images could we use?

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Hat52**
Closes #175 

### What new changes did you make? Tick all applicable boxes
- [ ] Added new abbreviation
- [ ] Fixed something in the source code
- [ x] Added a new feature
- [ ] Fixed the docs (README.md, CONTRIBTUING.md, etc)

### Describe the new changes you added.
Added meta tag for link sharing

### Share a screenshot of new changes
image
image

### CODE REVIEW

**Review by E-fais — APPROVED** [review]
LGTM

**Review by Njong392 — APPROVED** [review]
Wohooo! Approved 🎊 Thank you very much for these changes. Tomorrow, I'll create a tweet regarding this and see if the preview image thing works. I'll merge now, and reopen in case there's any problem. 

Do you have a Twitter handle? I'd like to give you credit for this on my Twitter 💜💜

**Comment by Njong392** [comment]
Hey @Hat52 this has already been merged but seems to not be working when i try to share the link on my socials. Is it possible to look at it again? If not, I can create a new issue for it.

**Comment by Hat52** [comment]
yeah sure, I will look into it.

**Pull request merged**
